"""agent/jit_harness/protocols.py — Protocol definitions for JIT harness system."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class GeneratedHarness:
    """A complete agent harness generated by the meta-model."""

    name: str
    files: dict[str, str]  # filename -> content
    task_description: str
    meta_prompt: str
    meta_response: str
    tokens_used: int = 0
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "files": self.files,
            "task_description": self.task_description,
            "meta_prompt": self.meta_prompt,
            "meta_response": self.meta_response,
            "tokens_used": self.tokens_used,
            "metadata": self.metadata,
        }


@dataclass
class SelectionResult:
    """Result of harness selection."""

    selected_harness: GeneratedHarness
    all_candidates: list[GeneratedHarness]
    scores: dict[str, float]  # harness_name -> score
    selector_type: str  # "logprob" or "judge"
    selection_reason: str
    metadata: dict = field(default_factory=dict)


@dataclass
class ExecutionResult:
    """Result of executing a harness."""

    success: bool
    final_answer: str
    score: float
    trajectory: list[dict]
    error: Optional[str] = None
    tokens_used: int = 0
    duration_s: float = 0.0
    metadata: dict = field(default_factory=dict)


class HarnessGeneratorProtocol(ABC):
    """Protocol for generating harnesses via a meta-model."""

    @abstractmethod
    async def generate(
        self,
        task: str,
        num_candidates: int = 3,
        reference_mode: str = "desc",  # "desc" or "code"
        reference_k: int = 3,
        **kwargs,
    ) -> list[GeneratedHarness]:
        """Generate N candidate harnesses for a task."""
        ...

    @abstractmethod
    async def health_check(self) -> bool:
        """Check if the meta-model endpoint is available."""
        ...


class HarnessSelectorProtocol(ABC):
    """Protocol for selecting the best harness from candidates."""

    @abstractmethod
    async def select(
        self,
        task: str,
        candidates: list[GeneratedHarness],
        **kwargs,
    ) -> SelectionResult:
        """Select the best harness from candidates."""
        ...


class HarnessExecutorProtocol(ABC):
    """Protocol for executing a selected harness."""

    @abstractmethod
    async def execute(
        self,
        harness: GeneratedHarness,
        task: str,
        **kwargs,
    ) -> ExecutionResult:
        """Execute the harness against a task."""
        ...


# Convenience types
HarnessCandidate = GeneratedHarness