"""packages.telemetry.trend_analysis.py — last30days-style trend analysis (issue #493).

Adapts the mvanhorn/last30days-skill workflow (30-day window, zero-config
GitHub + HN sources first, BYOK sources optional) on top of the existing
``agent.trend_watcher.TrendWatcher`` so the repo has ONE trend subsystem,
not two. Produces a decision-ready markdown summary in ``trends/`` and a
typed payload for the ``/trends`` admin endpoint in ``proxy.py``.

No external CLI is shelled out: TrendWatcher already covers the
last30days-skill's zero-config sources (github, hackernews) plus 11 more.
"""
from __future__ import annotations

import datetime as _dt
import logging
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

log = logging.getLogger("qwen-proxy")

TRENDS_DIR = Path("trends")
WINDOW_DAYS = 30


class TrendItem(BaseModel):
    model_config = {"extra": "forbid"}
    source: str
    title: str
    summary: str = ""
    url: str = ""
    relevance_score: float = 0.0
    published: str = ""
    tags: list[str] = Field(default_factory=list)


class TrendReport(BaseModel):
    model_config = {"extra": "forbid"}
    generated_at: str
    window_days: int = WINDOW_DAYS
    total_items: int
    sources: list[str]
    top_items: list[TrendItem]
    summary_path: str | None = None


def _within_window(published: str, days: int = WINDOW_DAYS) -> bool:
    """True if the ISO-ish published date falls within the last N days.

    Unparseable/missing dates are kept (fresh fetches are near-now anyway).
    """
    if not published:
        return True
    try:
        dt = _dt.datetime.fromisoformat(published.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=_dt.timezone.utc)
        age = _dt.datetime.now(_dt.timezone.utc) - dt
        return age.days <= days
    except ValueError:
        return True


async def run_trend_analysis(limit: int = 25) -> TrendReport:
    """Fetch trends via TrendWatcher, filter to a 30-day window, persist summary."""
    from agent.trend_watcher import TrendWatcher, get_trend_watcher

    watcher = get_trend_watcher() or TrendWatcher()
    alerts = await watcher.fetch()

    items = [
        TrendItem(**a.as_dict())
        for a in alerts
        if _within_window(a.as_dict().get("published", ""))
    ]
    items.sort(key=lambda i: i.relevance_score, reverse=True)
    top = items[:limit]

    now = _dt.datetime.now(_dt.timezone.utc)
    report = TrendReport(
        generated_at=now.isoformat(),
        total_items=len(items),
        sources=sorted({i.source for i in items}),
        top_items=top,
    )
    report.summary_path = _write_summary(report)
    return report


def _write_summary(report: TrendReport) -> str:
    """Write trends/trend_summary.md (and a dated copy); return the path."""
    TRENDS_DIR.mkdir(exist_ok=True)
    lines = [
        f"# AI/ML Trend Summary — last {report.window_days} days",
        "",
        f"Generated: {report.generated_at}",
        f"Items in window: {report.total_items} across {len(report.sources)} sources",
        "",
        "| # | Title | Source | Relevance | Link |",
        "|---|-------|--------|-----------|------|",
    ]
    for i, item in enumerate(report.top_items, 1):
        title = item.title.replace("|", "\\|")[:90]
        lines.append(
            f"| {i} | {title} | {item.source} | {item.relevance_score:.2f} | "
            f"{'[link](' + item.url + ')' if item.url else '—'} |"
        )
    lines.append("")
    lines.append("*Generated by trend_analysis.py (last30days-style window over TrendWatcher).*")
    content = "\n".join(lines) + "\n"

    path = TRENDS_DIR / "trend_summary.md"
    path.write_text(content, encoding="utf-8")
    dated = TRENDS_DIR / f"trend_summary_{_dt.date.today().isoformat()}.md"
    dated.write_text(content, encoding="utf-8")
    return str(path)
