#!/usr/bin/env bash
# branch_cleanup.sh — Stale branch pruning for autonomous-ai-agency
# Run from the repo root: bash scripts/branch_cleanup.sh
# Requires: git push access + gh CLI (or GITHUB_TOKEN for PR creation)

set -e
REPO="strikersam/autonomous-ai-agency"

echo "=== Fetching latest remote state ==="
git fetch --prune origin

# ─────────────────────────────────────────────
# STEP 1: DELETE MERGED BRANCHES
# ─────────────────────────────────────────────
MERGED_BRANCHES=(
  "chore/syncthing-merge"
  "claude/add-advisor-strategy-content-q0E3s"
  "claude/add-github-integration-jfTxU"
  "claude/advanced-rag-context-layer-VwkWj"
  "claude/auto-claude-shortcut-integration-KWYrR"
  "claude/context-issue-462"
  "claude/context-issue-467"
  "claude/deploy-and-fix-bugs-Ku3Yx"
  "claude/eloquent-johnson-7n3Kz"
  "claude/enhance-readme-seo-SKRt6"
  "claude/extract-blog-features-adPSt"
  "claude/fix-admin-login-readme-gDdEN"
  "claude/fix-github-auth-buttons-feFem"
  "claude/fix-ngrok-llm-access-5ZzFi"
  "claude/fix-pipeline-login-error-YOLhR"
  "claude/fix-pipeline-tests-Vg2lB"
  "claude/fix-two-issues-c2Dug"
  "claude/implement-agents-best-practices-eZtkW"
  "claude/implement-memory-feature-XHnbj"
  "claude/improve-repo-docs-9Q3eO"
  "claude/model-selection-mobile-MWY9M"
  "claude/nifty-pasteur-Ld6CG"
  "claude/pedantic-joliot-7ad51a"
  "claude/remove-vercel-fix-deployments-arqoH"
  "claude/review-and-update-readme-Ve7Zb"
  "claude/test-fix-model-ui-M3EYG"
  "claude/verify-local-models-SadEU"
  "codex/continue-hardening"
  "codex/local-coding-agent"
  "codex/local-ide-setup"
  "codex/remote-admin-control-plane"
  "conflict_270426_0659"
  "dependabot/npm_and_yarn/webui/frontend/all-patches-00e45958a7"
  "feat/orchestrator-run-cleanup"
  "fix-deploy"
  "fix/orchestrator-status-diagnostic"
  "fix/remove-orchestrator-status-diagnostic"
  "fix/triage-sweep-20260613"
)

echo ""
echo "=== Deleting ${#MERGED_BRANCHES[@]} MERGED branches ==="
for branch in "${MERGED_BRANCHES[@]}"; do
  echo -n "  Deleting origin/$branch ... "
  git push origin --delete "$branch" && echo "✓" || echo "⚠ skipped (already gone)"
done

# ─────────────────────────────────────────────
# STEP 2: DELETE PLAN-ONLY CONTEXT-ISSUE BRANCHES
# (single commit, just planning docs, no code, no open PR)
# ─────────────────────────────────────────────
PLAN_ONLY_BRANCHES=(
  "claude/context-issue-464"
  "claude/context-issue-470"
  "claude/context-issue-491"
  "claude/context-issue-493"
  "claude/context-issue-495"
  "claude/context-issue-511"
  "claude/context-issue-513"
  "claude/context-issue-517"
  "claude/context-issue-518"
  "claude/context-issue-526"
  "claude/context-issue-528"
  "claude/context-issue-530"
  "claude/context-issue-533"
  "claude/context-issue-540"
  "claude/context-issue-543"
)

echo ""
echo "=== Deleting ${#PLAN_ONLY_BRANCHES[@]} plan-only branches (just docs, no code) ==="
for branch in "${PLAN_ONLY_BRANCHES[@]}"; do
  echo -n "  Deleting origin/$branch ... "
  git push origin --delete "$branch" && echo "✓" || echo "⚠ skipped"
done

# ─────────────────────────────────────────────
# STEP 3: DELETE DEPENDABOT BRANCHES
# (auto-regenerated by Dependabot, safe to clear)
# ─────────────────────────────────────────────
DEPENDABOT_BRANCHES=(
  "dependabot/npm_and_yarn/frontend/all-patches-b56051be9e"
  "dependabot/npm_and_yarn/frontend/security-patches-47c4268404"
  "dependabot/pip/anthropic-gte-0.107.1"
  "dependabot/pip/beautifulsoup4-gte-4.15.0"
  "dependabot/pip/boto3-gte-1.43.24"
  "dependabot/pip/fakeredis-gte-2.36.1"
  "dependabot/pip/graphifyy-gte-0.8.35"
  "dependabot/pip/idna-gte-3.18"
  "dependabot/pip/python-multipart-gte-0.0.32"
  "dependabot/pip/redis-gte-8.0.0"
  "dependabot/pip/uvicorn-gte-0.49.0"
)

echo ""
echo "=== Deleting ${#DEPENDABOT_BRANCHES[@]} stale Dependabot branches ==="
for branch in "${DEPENDABOT_BRANCHES[@]}"; do
  echo -n "  Deleting origin/$branch ... "
  git push origin --delete "$branch" && echo "✓" || echo "⚠ skipped"
done

# ─────────────────────────────────────────────
# STEP 4: OPEN NEW PRs FOR UNIMPLEMENTED WORK
# These branches have real unmerged code but no open PR.
# Uses `gh` CLI. Run `gh auth login` first if needed.
# ─────────────────────────────────────────────
echo ""
echo "=== Creating PRs for branches with unimplemented work ==="

if ! command -v gh &>/dev/null; then
  echo "⚠  GitHub CLI (gh) not found. Install from https://cli.github.com and re-run."
  echo "   Branches needing PRs:"
  echo "     fix/ci-failures-2026-06-14           (19 commits — CI failure fixes)"
  echo "     fix/pipeline-thread-context-2026-06-14 (13 commits — JSONL pipeline fix)"
  echo "     fix/draft-pr-safety-2026-06-14        (14 commits — draft PR guard)"
  echo "     fix/ci-bandit-dockerfile-workflow-2026-06-14 (11 commits — bandit/CI)"
  echo "     claude/fix-onboarding-ice-add-ci-gate-1781417446 (12 commits — onboarding fix)"
  echo "     consolidate/maturation-stable          (14 commits — stability hardening)"
  echo "     fix/ceo-runtime-distribution           (6 commits — CEO runtime)"
  echo "     fix/ceo-multi-agent-swarm              (5 commits — multi-agent delegation)"
  echo "     fix/mongodb-skip-tests                 (5 commits — MongoDB CI skip)"
  echo "     claude/fix-brain-credits-priority-scanner-1781416838 (7 commits — credit drain fix)"
  echo "     feature/user-research-skill            (2 commits — new skill)"
  echo "     feat/enable-ecc                        (3 commits — ECC feature)"
  echo "     feat/scanner-subdomains-20260613       (1 commit  — subdomain scanner)"
  exit 0
fi

create_pr_if_needed() {
  local branch="$1"
  local title="$2"
  local body="$3"
  # Check if open PR already exists
  existing=$(gh pr list --head "$branch" --state open --json number -q '.[0].number' 2>/dev/null)
  if [ -n "$existing" ]; then
    echo "  ↩ $branch already has open PR #$existing"
    return
  fi
  echo -n "  Creating PR for $branch ... "
  gh pr create \
    --repo "$REPO" \
    --head "$branch" \
    --base master \
    --title "$title" \
    --body "$body" \
    --draft \
    && echo "✓" || echo "⚠ failed"
}

create_pr_if_needed \
  "fix/ci-failures-2026-06-14" \
  "fix(ci): resolve CI failures — Bandit alerts, deploy-cloudflare, frontend tests" \
  "Unmerged work from fix/ci-failures-2026-06-14 (19 commits). Previous PRs #604 and #606 were closed without merging. Reopening to land CI hardening."

create_pr_if_needed \
  "fix/pipeline-thread-context-2026-06-14" \
  "fix(pipeline): per-line JSONL validation and thread context fixes" \
  "Unmerged work from fix/pipeline-thread-context-2026-06-14 (13 commits). No prior PR. Pipeline threading and JSONL capture hardening."

create_pr_if_needed \
  "fix/draft-pr-safety-2026-06-14" \
  "fix(pipeline): protect draft PRs from auto-merge and housekeeping" \
  "Unmerged work (14 commits). Previous PR #599 was closed. Draft PR awareness guard for the AI pipeline."

create_pr_if_needed \
  "fix/ci-bandit-dockerfile-workflow-2026-06-14" \
  "fix(ci): npm ci resilience, bandit nosec annotations, re-enable Dockerfile checks" \
  "Unmerged work (11 commits). No prior PR was opened for this branch."

create_pr_if_needed \
  "claude/fix-onboarding-ice-add-ci-gate-1781417446" \
  "fix(onboarding): remove NameError ice bug + add CI regression gate" \
  "Unmerged work (12 commits). Previous PR #617 was closed. Restores two-pass provider resolver and adds CI gate."

create_pr_if_needed \
  "claude/fix-brain-credits-priority-scanner-1781416838" \
  "fix(brain): stop Anthropic credit drain + persist provider choice" \
  "Unmerged work (7 commits). Previous PR #616 was closed. Critical fix: never auto-pick paid Anthropic models."

create_pr_if_needed \
  "consolidate/maturation-stable" \
  "chore(stability): maturation hardening — test updates and stability fixes" \
  "Unmerged work (14 commits). Prior PRs #557, #558, #588 were all closed. Stability and test assertion updates."

create_pr_if_needed \
  "fix/ceo-runtime-distribution" \
  "feat(ceo): use RuntimeManager for real runtime distribution" \
  "Unmerged work (6 commits). Previous PR #615 was closed."

create_pr_if_needed \
  "fix/ceo-multi-agent-swarm" \
  "feat(orchestrator): real CEO delegation + wake sleeping runtimes" \
  "Unmerged work (5 commits). Previous PR #614 was closed."

create_pr_if_needed \
  "fix/mongodb-skip-tests" \
  "fix(ci): skip MongoDB-dependent tests when no MongoDB available" \
  "Unmerged work (5 commits). Previous PRs #483, #484 were closed."

create_pr_if_needed \
  "feature/user-research-skill" \
  "feat(skills): user research skill" \
  "Unmerged work (2 commits). No prior PR. New user research skill with test fixes."

create_pr_if_needed \
  "feat/enable-ecc" \
  "feat: enable ECC" \
  "Unmerged work (3 commits). No prior PR."

create_pr_if_needed \
  "feat/scanner-subdomains-20260613" \
  "feat(scanner): subdomain enumeration layer" \
  "Unmerged work (1 commit). Previous PR #585 was closed. Adds _scan_subdomains probe."

echo ""
echo "=== Done! ==="
echo "Branches with open PRs (untouched):"
echo "  claude/context-issue-485   PR #613"
echo "  claude/context-issue-504   PR #603"
echo "  claude/cool-davinci-494siy PR #591"
echo "  feat/e2e-polish-final-20260613  PR #592"
echo "  fix/premortem-remaining-20260613 PR #590"
echo "  handoff/session-2026-06-15 PR #602"
echo "  (plus PR #618 and #619 — branches not found in remote)"
