"""Sync the README screenshot gallery from the organized screenshot inventory."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

START_MARKER = "<!-- README_UI_GALLERY:START -->"
END_MARKER = "<!-- README_UI_GALLERY:END -->"


@dataclass(frozen=True)
class Screenshot:
    path: str
    alt: str
    width: str = "92%"


@dataclass(frozen=True)
class GallerySection:
    heading: str
    summary: str
    screenshots: tuple[Screenshot, ...]


# Paths point at the most recent captured screenshot set (docs/screenshots/v5/),
# generated by scripts/capture_screens.py against a live v5 build.
GALLERY: tuple[GallerySection, ...] = (
    GallerySection(
        heading="### 💬 Chat — unified assistant",
        summary='Talk to the CEO agent directly; it decomposes goals and routes work to the right specialists.',
        screenshots=(Screenshot("docs/screenshots/v5/chat.png", '💬 Chat — unified assistant'),),
    ),
    GallerySection(
        heading="### 📊 Dashboard — system overview",
        summary='Live agent health, recent activity, and system metrics at a glance.',
        screenshots=(Screenshot("docs/screenshots/v5/dashboard.png", '📊 Dashboard — system overview'),),
    ),
    GallerySection(
        heading="### 🗂 Tasks — job lifecycle board",
        summary='Every AI job made visible: waiting, running, blocked, in review, or done.',
        screenshots=(Screenshot("docs/screenshots/v5/tasks.png", '🗂 Tasks — job lifecycle board'),),
    ),
    GallerySection(
        heading="### 🤖 Agents — autonomous team",
        summary='Your specialist roster — each with its own model, runtime, specialty, and guardrails.',
        screenshots=(Screenshot("docs/screenshots/v5/agents.png", '🤖 Agents — autonomous team'),),
    ),
    GallerySection(
        heading="### 🗓 Schedules — autopilot jobs",
        summary='Recurring and scheduled autonomous work.',
        screenshots=(Screenshot("docs/screenshots/v5/schedules.png", '🗓 Schedules — autopilot jobs'),),
    ),
    GallerySection(
        heading="### ⚡ Skills — agentic capabilities",
        summary='Reusable runtime skills bound to specialists.',
        screenshots=(Screenshot("docs/screenshots/v5/skills.png", '⚡ Skills — agentic capabilities'),),
    ),
    GallerySection(
        heading="### 🎯 Portfolio — WSJF roadmap",
        summary='Prioritised initiatives, sprints, and agile health.',
        screenshots=(Screenshot("docs/screenshots/v5/portfolio.png", '🎯 Portfolio — WSJF roadmap'),),
    ),
    GallerySection(
        heading="### 📈 Intelligence — trends & competitors",
        summary="Trend and competitor signals scoped to each onboarded company's stack.",
        screenshots=(Screenshot("docs/screenshots/v5/intelligence.png", '📈 Intelligence — trends & competitors'),),
    ),
    GallerySection(
        heading="### 📚 Knowledge — docs & sources",
        summary="Wiki pages, source material, and reusable context — your team's memory.",
        screenshots=(Screenshot("docs/screenshots/v5/knowledge.png", '📚 Knowledge — docs & sources'),),
    ),
    GallerySection(
        heading="### 🔌 Providers — models, Ollama & MCP",
        summary='Connect free/cloud/local AI sources and choose which models are available.',
        screenshots=(Screenshot("docs/screenshots/v5/providers.png", '🔌 Providers — models, Ollama & MCP'),),
    ),
    GallerySection(
        heading="### 🔭 Logs — traces & observability",
        summary='Every LLM call: tokens, latency, cost, and decision context.',
        screenshots=(Screenshot("docs/screenshots/v5/logs.png", '🔭 Logs — traces & observability'),),
    ),
    GallerySection(
        heading="### 🐙 GitHub — repos & PRs",
        summary="Connect repositories and manage the agent's delivery surface.",
        screenshots=(Screenshot("docs/screenshots/v5/github.png", '🐙 GitHub — repos & PRs'),),
    ),
    GallerySection(
        heading="### 🏢 Company — operating context",
        summary="An onboarded company's detected stack, systems, and SEO/health.",
        screenshots=(Screenshot("docs/screenshots/v5/company.png", '🏢 Company — operating context'),),
    ),
    GallerySection(
        heading="### ✨ Onboarding — setup wizard",
        summary='Scan a website and stand up its specialist agency in minutes.',
        screenshots=(Screenshot("docs/screenshots/v5/onboarding.png", '✨ Onboarding — setup wizard'),),
    ),
    GallerySection(
        heading="### 🩺 Doctor — diagnostics",
        summary='System self-checks and autonomy readiness probes.',
        screenshots=(Screenshot("docs/screenshots/v5/doctor.png", '🩺 Doctor — diagnostics'),),
    ),
    GallerySection(
        heading="### 🛡 Admin — users & access",
        summary='Manage users, roles, instance activation, and onboarding gates.',
        screenshots=(Screenshot("docs/screenshots/v5/admin.png", '🛡 Admin — users & access'),),
    ),
    GallerySection(
        heading="### 📱 Mobile",
        summary="Responsive layout — sign in, view the dashboard, and work the task board from a phone.",
        screenshots=(
            Screenshot("docs/screenshots/v5/mobile-login.png", "Mobile login", width="30%"),
            Screenshot("docs/screenshots/v5/mobile-dashboard.png", "Mobile dashboard", width="30%"),
            Screenshot("docs/screenshots/v5/mobile-tasks.png", "Mobile task board", width="30%"),
        ),
    ),
)


def build_gallery() -> str:
    blocks: list[str] = []
    for section in GALLERY:
        blocks.append(section.heading)
        blocks.append("")
        blocks.append(section.summary)
        blocks.append("")
        if len(section.screenshots) == 1:
            shot = section.screenshots[0]
            blocks.append(
                f'<p align="center"><img src="{shot.path}" width="{shot.width}" alt="{shot.alt}"/></p>'
            )
        else:
            image_lines = ["<p align=\"center\">"]
            for index, shot in enumerate(section.screenshots):
                image_lines.append(
                    f'  <img src="{shot.path}" width="{shot.width}" alt="{shot.alt}"/>'
                )
                if index != len(section.screenshots) - 1:
                    image_lines.append("  &nbsp;")
            image_lines.append("</p>")
            blocks.append("\n".join(image_lines))
        blocks.append("")
    return "\n".join(blocks).strip()


def replace_gallery_block(readme_text: str, gallery_text: str) -> str:
    start = readme_text.index(START_MARKER) + len(START_MARKER)
    end = readme_text.index(END_MARKER)
    return f"{readme_text[:start]}\n{gallery_text}\n{readme_text[end:]}"


def sync_readme_gallery(readme_path: Path) -> None:
    current = readme_path.read_text(encoding="utf-8")
    updated = replace_gallery_block(current, build_gallery())
    readme_path.write_text(updated, encoding="utf-8")


def write_manifest(manifest_path: Path) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    payload = [
        {
            "heading": section.heading,
            "summary": section.summary,
            "screenshots": [asdict(shot) for shot in section.screenshots],
        }
        for section in GALLERY
    ]
    manifest_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    readme_path = Path("README.md")
    sync_readme_gallery(readme_path)
    write_manifest(Path("docs/screenshots/manifest.json"))
    print(f"Updated: {readme_path}")
    print("Updated: docs/screenshots/manifest.json")


if __name__ == "__main__":
    main()
